### ISSUE TITLE
can't go get 

### ISSUE THREAD

**Issue by czyCoder** [furkansenharputlu/f-license#22] opened 2020-09-27 08:25 UTC
go get github.com/furkansenharputlu/f-license/client
go get github.com/furkansenharputlu/f-license/client: no matching versions for query "upgrade"

**Comment by furkansenharputlu** [comment] 2020-09-29 14:15
Thanks for reporting this issue! However, I cannot reproduce it. Can you please provide more details and steps?

**Comment by furkansenharputlu** [comment] 2021-04-04 03:09
Closing this issue for now. If you see the same problem, feel free to open it.

**Closed by furkansenharputlu** 2021-04-04 03:09 UTC
